-- Create podcasts table to store episode metadata
CREATE TABLE episodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  published_at DATETIME,
  duration INTEGER, -- Duration in seconds
  audio_key TEXT NOT NULL,  -- R2 key for the audio file
  thumbnail_key TEXT NOT NULL, -- R2 key for the thumbnail
  transcript TEXT,           -- Generated by Workers AI
  status TEXT CHECK(status IN ('draft', 'published')) NOT NULL DEFAULT 'draft',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX idx_episodes_status ON episodes(status);
CREATE INDEX idx_episodes_audio_key ON episodes(audio_key);

-- Create trigger to update episodes.updated_at
CREATE TRIGGER episodes_updated_at 
  AFTER UPDATE ON episodes
BEGIN
  UPDATE episodes 
  SET updated_at = CURRENT_TIMESTAMP 
  WHERE id = NEW.id;
END;